apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitwarden

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - service.yaml
  - secret.yaml
  - ingress.yaml
  - statefulset.yaml
