---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitwarden
  labels:
    app: bitwarden

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitwarden
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "bitwarden"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - "bitwarden-smtp"
      - "bitwarden-tls"
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitwarden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bitwarden
subjects:
- kind: ServiceAccount
  name: bitwarden