---
collections:
  - name: community.kubernetes
    version: "1.2.1"
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "2.4.2"
  - name: cloud.common
    version: "2.1.4"
