apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.21.0/controller.yaml
  - namespace.yaml