apiVersion: v1
kind: Secret
metadata:
  name: guacamole-database-credentials
  namespace: guacamole
data:
  postgres-user: Z3VhY2Ftb2xl
  postgres-password: U3VwZXJzZWNyZXQ=
  postgres-hostname: cG9zdGdyZXMtaG9zdA==
  postgres-port: NTQzMg==
  postgres-database: Z3VhY2Ftb2xl
type: Opaque
